package com.mycompany.figuras;

public class VentanaCilindro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCilindro.class.getName());

    /**
     * Creates new form Cilindro
     */
    public VentanaCilindro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Radio = new javax.swing.JLabel();
        Altura = new javax.swing.JLabel();
        Camporadio = new javax.swing.JTextField();
        Campoaltura = new javax.swing.JTextField();
        CalcularCilindro = new javax.swing.JButton();
        VolumenC = new javax.swing.JLabel();
        SuperficieC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cilindro");

        Radio.setText("Radio (cms)");

        Altura.setText("Altura (cms)");

        CalcularCilindro.setText("Calcular");
        CalcularCilindro.addActionListener(this::CalcularCilindroActionPerformed);

        VolumenC.setText("Volumen (cm3): ");

        SuperficieC.setText("Superficie (cm2):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CalcularCilindro, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(Campoaltura)
                    .addComponent(Camporadio))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Altura)
                    .addComponent(VolumenC, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addComponent(SuperficieC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radio)
                    .addComponent(Camporadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campoaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Altura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CalcularCilindro)
                .addGap(18, 18, 18)
                .addComponent(VolumenC)
                .addGap(18, 18, 18)
                .addComponent(SuperficieC)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularCilindroActionPerformed
        try {
            if (Camporadio.getText().isBlank() || Campoaltura.getText().isBlank()) {

                javax.swing.JOptionPane.showMessageDialog(this, "Error: Debes ingresar radio y altura", "Campos vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            double radio = Double.parseDouble(Camporadio.getText());
            double altura = Double.parseDouble(Campoaltura.getText());
            if ((radio < 0) || (altura < 0)) {

                javax.swing.JOptionPane.showMessageDialog(this, "Error: El radio y altura deben ser valores positivos");
                return;
            }
            Cilindro cilindro = new Cilindro(radio, altura);
            double volumen = cilindro.calcularVolumen();
            double superficie = cilindro.calcularSuperficie();
            VolumenC.setText("Volumen (cm3): " + String.format("%.2f", volumen));
            SuperficieC.setText("Superficie (cm2): " + String.format("%.2f", superficie));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Uno de los valores ingresados no es un número válido.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CalcularCilindroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new VentanaCilindro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura;
    private javax.swing.JButton CalcularCilindro;
    private javax.swing.JTextField Campoaltura;
    private javax.swing.JTextField Camporadio;
    private javax.swing.JLabel Radio;
    private javax.swing.JLabel SuperficieC;
    private javax.swing.JLabel VolumenC;
    // End of variables declaration//GEN-END:variables
}
