package com.mycompany.figuras;

public class VentanaPiramide extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPiramide.class.getName());

    /**
     * Creates new form VentanaPiramide
     */
    public VentanaPiramide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JLabel();
        Altura = new javax.swing.JLabel();
        Apotema = new javax.swing.JLabel();
        CampoBase = new javax.swing.JTextField();
        CampoAltura = new javax.swing.JTextField();
        CampoApotema = new javax.swing.JTextField();
        CalcularPiramide = new javax.swing.JButton();
        VolumenP = new javax.swing.JLabel();
        SuperficieP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Piramide");

        Base.setText("Base (cms)");

        Altura.setText("Altura (cms)");

        Apotema.setText("Apotema (cms)");

        CalcularPiramide.setText("Calcular");
        CalcularPiramide.addActionListener(this::CalcularPiramideActionPerformed);

        VolumenP.setText("Volumen (cm3): ");

        SuperficieP.setText("Superficie (cm2):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SuperficieP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addComponent(VolumenP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Base)
                            .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apotema))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CalcularPiramide, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CampoBase, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(CampoAltura)
                                .addComponent(CampoApotema)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Base)
                    .addComponent(CampoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Altura)
                    .addComponent(CampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apotema)
                    .addComponent(CampoApotema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(CalcularPiramide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VolumenP)
                .addGap(18, 18, 18)
                .addComponent(SuperficieP)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularPiramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularPiramideActionPerformed
        try {
            if (CampoBase.getText().isBlank() || CampoAltura.getText().isBlank() || CampoApotema.getText().isBlank()) {

                javax.swing.JOptionPane.showMessageDialog(this, "Error: Debes ingresar Base, altura y Apotema", "Campos vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            double Base = Double.parseDouble(CampoBase.getText());
            double Altura = Double.parseDouble(CampoAltura.getText());
            double Apotema = Double.parseDouble(CampoApotema.getText());
            if ((Base < 0) || (Altura < 0) || (Apotema < 0)) {

                javax.swing.JOptionPane.showMessageDialog(this, "Error: La Base, Altura y Apotema deben ser valores positivos");
                return;
            }
            Piramide piramide = new Piramide(Base, Altura, Apotema);
            double volumen = piramide.calcularVolumen();
            double superficie = piramide.calcularSuperficie();
            VolumenP.setText("Volumen (cm3): " + String.format("%.2f", volumen));
            SuperficieP.setText("Superficie (cm2): " + String.format("%.2f", superficie));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Uno de los valores ingresados no es un número válido.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CalcularPiramideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPiramide().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura;
    private javax.swing.JLabel Apotema;
    private javax.swing.JLabel Base;
    private javax.swing.JButton CalcularPiramide;
    private javax.swing.JTextField CampoAltura;
    private javax.swing.JTextField CampoApotema;
    private javax.swing.JTextField CampoBase;
    private javax.swing.JLabel SuperficieP;
    private javax.swing.JLabel VolumenP;
    // End of variables declaration//GEN-END:variables
}
