package notas;

public class VentanaPrincipal extends javax.swing.JFrame {

    Notas misNotas = new Notas();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nota1 = new javax.swing.JLabel();
        Nota2 = new javax.swing.JLabel();
        Nota3 = new javax.swing.JLabel();
        Nota5 = new javax.swing.JLabel();
        Nota4 = new javax.swing.JLabel();
        Camponota2 = new javax.swing.JTextField();
        Camponota1 = new javax.swing.JTextField();
        Camponota3 = new javax.swing.JTextField();
        Camponota4 = new javax.swing.JTextField();
        Camponota5 = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Promedio = new javax.swing.JLabel();
        Desviacion = new javax.swing.JLabel();
        Mayor = new javax.swing.JLabel();
        Menor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notas");
        setResizable(false);

        Nota1.setText("Nota 1:");

        Nota2.setText("Nota 2:");

        Nota3.setText("Nota 3");

        Nota5.setText("Nota 5");

        Nota4.setText("Nota 4");

        Camponota3.addActionListener(this::Camponota3ActionPerformed);

        Calcular.setText("Calcular");
        Calcular.addActionListener(this::CalcularActionPerformed);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(this::LimpiarActionPerformed);

        Promedio.setText("Promedio = ");

        Desviacion.setText("Desviacion Estandar = ");

        Mayor.setText("Mayor = ");

        Menor.setText("Menor = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nota5)
                            .addComponent(Nota4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nota2)
                                .addComponent(Nota1))
                            .addComponent(Nota3))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Camponota2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Camponota5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Camponota4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Camponota3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Camponota1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Calcular)
                                .addGap(18, 18, 18)
                                .addComponent(Limpiar))
                            .addComponent(Promedio)
                            .addComponent(Desviacion)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Mayor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Menor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Camponota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Camponota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nota3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Camponota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nota4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Camponota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nota5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Camponota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcular)
                    .addComponent(Limpiar))
                .addGap(18, 18, 18)
                .addComponent(Promedio)
                .addGap(18, 18, 18)
                .addComponent(Desviacion)
                .addGap(18, 18, 18)
                .addComponent(Mayor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Menor)
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        try {
            if (Camponota1.getText().isBlank() || Camponota2.getText().isBlank() || Camponota3.getText().isBlank() || Camponota4.getText().isBlank() || Camponota5.getText().isBlank()) {

                javax.swing.JOptionPane.showMessageDialog(this, "Error: Debes ingresar las 5 notas.", "Campos vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            double n1 = Double.parseDouble(Camponota1.getText());
            double n2 = Double.parseDouble(Camponota2.getText());
            double n3 = Double.parseDouble(Camponota3.getText());
            double n4 = Double.parseDouble(Camponota4.getText());
            double n5 = Double.parseDouble(Camponota5.getText());
            if ((n1 < 0 || n1 > 5) || (n2 < 0 || n2 > 5) || (n3 < 0 || n3 > 5)
                    || (n4 < 0 || n4 > 5) || (n5 < 0 || n5 > 5)) {

                javax.swing.JOptionPane.showMessageDialog(this, "Error: Las notas deben estar entre 0 y 5.");
                return;
            }
            misNotas.Listanotas[0] = n1;
            misNotas.Listanotas[1] = n2;
            misNotas.Listanotas[2] = n3;
            misNotas.Listanotas[3] = n4;
            misNotas.Listanotas[4] = n5;
            Promedio.setText("Promedio = " + String.format("%.2f", misNotas.calcularPromedio()));
            Desviacion.setText("Desviacion Estandar = " + String.format("%.2f", misNotas.calcularDesviacion()));
            Mayor.setText("Mayor valor = " + misNotas.calcularMayor());
            Menor.setText("Menor valor = " + misNotas.calcularMenor());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Uno de los valores ingresados no es un número válido.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CalcularActionPerformed

    private void Camponota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camponota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camponota3ActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        Camponota1.setText("");
        Camponota2.setText("");
        Camponota3.setText("");
        Camponota4.setText("");
        Camponota5.setText("");
        Promedio.setText("Promedio = ");
        Desviacion.setText("Desviacion Estandar = ");
        Mayor.setText("Mayor = ");
        Menor.setText("Menor = ");
        for (int i = 0; i < misNotas.Listanotas.length; i++) {
            misNotas.Listanotas[i] = 0;
        }
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField Camponota1;
    private javax.swing.JTextField Camponota2;
    private javax.swing.JTextField Camponota3;
    private javax.swing.JTextField Camponota4;
    private javax.swing.JTextField Camponota5;
    private javax.swing.JLabel Desviacion;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Mayor;
    private javax.swing.JLabel Menor;
    private javax.swing.JLabel Nota1;
    private javax.swing.JLabel Nota2;
    private javax.swing.JLabel Nota3;
    private javax.swing.JLabel Nota4;
    private javax.swing.JLabel Nota5;
    private javax.swing.JLabel Promedio;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
